from pyrogram import Client, filters
from bot.info import Config

@Client.on_message(filters.command("start") & filters.private)
async def start(bot, message):
    user = message.from_user
    
    text = f"""
👋 **Hello {user.mention}!**

I am the **Dedicated Streamer Node** (Oracle Cloud).
My job is to provide high-speed **Download & Stream** links for **AnimeToki**.

⚙️ **System Commands (Owner Only):**
• `/stats` - Check Oracle Bandwidth & Server Health
• `/restart` - Restart the Bot (Apply Updates)

🔐 **Auth Management:**
• `/add [user_id]` - Authorize a new user
• `/remove [user_id]` - Revoke access
• `/users` - List all authorized users

🚀 **How to use?**
You don't need to do anything here!
Just click on the **Download/Watch** links generated by the Main Bot, and I will stream the file for you.
    """
    
    await message.reply_text(
        text=text,
        quote=True,
        disable_web_page_preview=True
    )
